application: belay-stickies
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: launch.py

- url: /generate
  script: generate.py

- url: /data
  script: data.py

- url: /(.*\.(html|css|js|png))
  script: lib/CORSstatic.py
